baseURL = "https://youthformusic.com"
defaultContentLanguage = "en"
disableLanguages = ["ar"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Youth For Music Association"
[languages.ar]
contentDir = "content/arabic"
copyright = "Copyright &copy; 2020 All Rights Reserved"
home = "الصفحة الرئيسية"
languageCode = "ar-ar"
languageName = "Arabic"
languagedirection = "rtl"
weight = 1
[[languages.ar.menu.main]]
hasChildren = true
name = "معلومات عنا"
weight = 1
[[languages.ar.menu.main]]
Parent = "معلومات عنا"
URL = "about"
name = "عن الجمعية"
weight = 1
[[languages.ar.menu.main]]
Parent = "معلومات عنا"
URL = "#"
name = "المؤسسون"
weight = 2
[[languages.ar.menu.main]]
hasChildren = true
name = "المشاريع"
weight = 2
[[languages.ar.menu.main]]
Parent = "المشاريع"
URL = "#"
name = "أوركسترا الأردن للشباب"
weight = 1
[[languages.ar.menu.main]]
URL = "blog"
name = "المدونه"
weight = 5
[[languages.ar.menu.main]]
URL = "contact"
name = "تواصلوا معنا"
weight = 9
[languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "English"
weight = 0
[[languages.en.menu.main]]
hasChildren = true
name = "About Us"
weight = 1
[[languages.en.menu.main]]
Parent = "About Us"
URL = "about"
name = "About YMA"
weight = 1
[[languages.en.menu.main]]
Parent = "About Us"
URL = "goals"
name = "Our Goals"
weight = 2
[[languages.en.menu.main]]
Parent = "About Us"
URL = "mission"
name = "Mission & Vision"
weight = 3
[[languages.en.menu.main]]
URL = "about"
name = "Founding Members"
weight = 2
[[languages.en.menu.main]]
hasChildren = true
name = "Projects"
weight = 2
[[languages.en.menu.main]]
Parent = "Projects"
URL = "#"
name = "Jordan Youth Orchestra"
weight = 1
[[languages.en.menu.main]]
Parent = "Projects"
URL = "#"
name = "Webinars"
weight = 2
[[languages.en.menu.main]]
URL = "blog"
name = "Newsroom"
weight = 5
[[languages.en.menu.main]]
URL = "contact"
name = "Contact Us"
weight = 9
[[menu.footer]]
URL = "about"
name = "About"
weight = 1
[[menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[params]
author = ""
contact_form_action = "#"
description = "This is meta description"
email = "contactus@youthformusic.com"
google_analitycs_id = ""
location = "Amman, Jordan"
logo = "images/youth-music-association-logo_2.png"
mobile = "+962 77 014 3406"
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = false
label = "Get A Quote"
link = "contact"
[params.navigation]
about = "About Us"
contact = "Contact Us"
founders = "Founding Members"
projects = "Projects"
youth_orchestra = "Jordan Youth Orchestra"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com/Youthformusic/"
[[params.social]]
icon = "ion-social-instagram-outline"
link = "https://instagram.com/youthformusic"
[[params.social]]
icon = "ion-ios-email-outline"
link = "mailto:contactus@youthformusic.com"
